defaults:
  - _self_
  - experiment: physionet  # sc09

train: # Not used in generate.py
  name: null # Name of experiment (prefix of experiment name)
  ckpt_iter: max
  iters_per_ckpt: 2000
  iters_per_logging: 1000 # 100
  n_iters: 1000001
  learning_rate: 2e-4
  batch_size_per_gpu: 64  # 4
  results_path: /mnt/data/lisa/ecg_results/sashimi

generate:
  ckpt_iter: max # Which checkpoint to use; assign a number or "max". Is ignored when sampling during training
  ckpt_smooth: null # Which checkpoint to start averaging from (experimental feature, can ignore)
  n_samples: 2 # Number of utterances to be generated (per GPU)
  batch_size: null # Number of samples to generate at once per GPU. null means max (equal to samples_per_gpu)
  mel_path: null # Folder of preprocessed spectrograms (optional)
  mel_name: null # Name of specific spectrogram to condition on (set to null for unconditional, set to an audio file name for vocoding)

distributed:
  dist_backend: nccl
  dist_url: tcp://localhost:54321

denoising:
  name: bw
  f_c_min: 0 #0
  f_c_max: 1 # 0.7
  l1reg: 10 # 0.1
  l2reg: 10
  J: 100
  n_leads: 9
  amplitude: 1
  T: 20
  N: 50


wandb:
  mode: online # Pass in 'wandb.mode=online' to turn on wandb logging
  project: sashimi
  entity: phdlisa  # phdgabriel
  id: null # Set to string to resume logging from run
  job_type: training