hydra:
  run:
    dir: ./outputs/debug # exp1/${now:%Y-%m-%d}/${now:%H-%M-%S}

wandb:
  mode: online # Pass in 'wandb.mode=online' to turn on wandb logging
  project: baseline_AE
  entity: phdgabriel
  id: null # Set to string to resume logging from run
  job_type: training

defaults:
  - baseline: AAE
  - paths: beat_no_norm