name: null # Name of experiment (prefix of experiment name)
ckpt_iter: max
iters_per_ckpt: 10
iters_per_logging: 2
n_iters: 10_000
learning_rate_final: 1e-4
learning_rate_start: 1e-4
n_transition_steps: 1e5
batch_size_per_gpu: 64
decay: 0.9999